[package]
name = "magic_sandbox"
version = "0.1.0"
edition = "2021"
authors = ["wn"]

[[bin]]
name = "magic_sandbox"
path = "src/main.rs"

[workspace]

[dependencies]
magic_sandbox_lib = { path = "magic_sandbox_lib" }
pollster = "0.3"
js-sys = "0.3.61"
web-sys = "0.3.64"
