name: build_wasm

on:
  push:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: wasm-pack-action
      uses: jetli/wasm-pack-action@v0.3.0
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y liblua5.3-dev pkg-config build-essential libc6-dev
    - name: Build 🛠
      run: wasm-pack build --release --target web magic_sandbox_lib
    - name: Archive 💼
      run: |
        echo "- builed files -"
        ls -f magic_sandbox_lib/pkg
        echo "----------------"
        mkdir dest
        mkdir dest/magic_sandbox_lib
        cp -r magic_sandbox_lib/pkg dest/magic_sandbox_lib
        echo "-  clone main  -"
        git clone https://github.com/wavelet-noise/magic_sandbox.git repo
        ls -f repo
        echo "----------------"
        cp repo/index.html dest/index.html
        cp repo/favicon.ico dest/favicon.ico
        cp -r repo/assets dest/assets
        rm -f dest/magic_sandbox_lib/pkg/.gitignore
        echo "---  result  ---"
        ls -fR dest
    - name: Deploy 🚀
      uses: s0/git-publish-subdir-action@develop
      env:
        REPO: self
        BRANCH: gh-pages
        FOLDER: dest
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
